name: Build & Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:    
      - '*'

env:
  ORG_GRADLE_PROJECT_NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
  ORG_GRADLE_PROJECT_NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
  ORG_GRADLE_PROJECT_SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
  ORG_GRADLE_PROJECT_SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
  ORG_GRADLE_PROJECT_SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}

jobs:

  build-on-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Cache Build Tooling
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.konan
          key: ${{ runner.os }}-gradle-${{ hashFiles('*.gradle.kts') }}

      - name: Build sqllin-driver
        run: ./gradlew :sqllin-driver:assemble

      - name: Run sqllin-driver Linux X64 Tests
        run: ./test_driver_linux.sh

      - name: Run sqllin-driver JVM Unit Tests on Linux X64
        run: ./test_driver_jvm.sh

      - name: Build sqllin-processor
        run: ./gradlew :sqllin-processor:assemble

      - name: Build sqllin-dsl
        run: ./gradlew :sqllin-dsl:assemble

      - name: Run sqllin-dsl Linux X64 Tests
        run: ./test_dsl_linux.sh

      - name: Run sqllin-dsl JVM Unit Tests on Linux X64
        run: ./test_dsl_jvm.sh

      - name: Gradle Cache
        uses: gradle/gradle-build-action@v2

      - name: AVD Cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-26

      - name: Create AVD and Generate Snapshot for Caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 26
          target: default
          arch: x86_64
          profile: pixel_2
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: Run Android 8 Instrumented Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 26
          target: default
          arch: x86_64
          profile: pixel_2
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./test_android.sh

      - name: Upload sqllin-driver Reports
        uses: actions/upload-artifact@v2
        with:
          name: Test-Reports
          path: sqllin-driver/build/reports
        if: always()

      - name: Upload sqllin-dsl Reports
        uses: actions/upload-artifact@v2
        with:
          name: Test-Reports
          path: sqllin-dsl/build/reports
        if: always()
